services:
  _defaults: { public: true, autoconfigure: true, autowire: true }
  underscore:
    alias: sonata.admin.label.strategy.underscore
  admin.abstract:
    class: App\Admin\AbstractAdmin
    abstract: true

  sonata.user.admin.user:
    class: App\Admin\UserAdmin
    arguments: [ '@sonata.user.manager.user' ]
    tags:
      - { name: sonata.admin, manager_type: orm, model_class: App\Entity\User, group: sonata_user, label: users, icon: '<i class="fa fa-user"></i>', show_in_roles_matrix: false, translation_domain: 'SonataUserBundle',label_translator_strategy: underscore }
    public: true
    
  admin.company:
    class: App\Admin\CompanyAdmin
    parent: admin.abstract
    tags:
        - { name: sonata.admin, manager_type: orm, model_class: App\Entity\Company, controller: App\Controller\CompanyAdminController, group: admin, label: company_label, label_translator_strategy: underscore }
    calls:
        - [setTemplate,['edit','app/company/edit.html.twig']]
