sonata_admin:
    title: 'Enterprise HUB'
    title_logo: images/logo_transparente.png
    security:
        handler: sonata.admin.security.handler.role

    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    
    options:
        skin: 'skin-blue-light'
        logo_content: 'icon'
    templates:
        layout: 'base.html.twig'
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
