# Production environment override
services:
  redis:
    image: redis:5-alpine
    networks:
      - entreprisehub
    ports: [ "6379" ]
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
